spring:
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  datasource:
    driverClassName: org.h2.Driver
    username: admin
    password: password
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: test